### ISSUE TITLE
It converted only a portion of the files

### ISSUE THREAD

**Issue by gerroon** [marph91/jimmy#26]
**Describe the bug**
I have like 350 .tid files from tiddlywiki  JS version. It converted only 14 files out of the whole thing. I used `jimmy [folderto tids]`

**OS**
Debian

 
**To Reproduce**
Please provide a minimal example file for debugging.

[aaaa.tar.gz](https://github.com/user-attachments/files/17962355/aaaa.tar.gz)

**Comment by marph91** [comment]
Thanks for the report.

1. For now, only individual `.tid` files can be converted. But I will extend the script to support a folder of `.tid` files, too.
2. There might be an issue with the format. There is much (unexpected) HTML in the notes. Did you export by `Export tiddler -> TID text file`?

![grafik](https://github.com/user-attachments/assets/4ede9d8f-08a8-44bb-ab3f-fcdbc189009d)

Tomorrow I will have likely some time to look closer at it.

**Comment by gerroon** [comment]
I just converted the original tid folder. I am not aware a method of exporting all of them at one go.

**Comment by marph91** [comment]
Turned out that [HTML blocks can be contained in Wikitext](https://tiddlywiki.com/#HTML%20in%20WikiText). That makes things complicated. But at the end I figured out some implementation (though it's not perfect). Can you try [the latest release](https://github.com/marph91/jimmy/releases/tag/v0.0.37)?

The command should be like described at the [documentation](https://marph91.github.io/jimmy/formats/tiddlywiki/):
`jimmy-cli-linux /folder/to/tiddlers --format tiddlywiki`

**Comment by gerroon** [comment]
Hi

Thanks for the update. I am getting different kind of error

```
[11/30/24 19:19:05] INFO     Jimmy 0.0.37 (Pandoc 3.5)
                    INFO     Importing notes from "/home/USER/tidwiki/tiddlers"
                    INFO     Start parsing
Traceback (most recent call last):
  File "jimmy_cli.py", line 139, in <module>
  File "jimmy_cli.py", line 135, in main
  File "jimmy.py", line 123, in jimmy
  File "jimmy.py", line 80, in convert_all_inputs
  File "converter.py", line 66, in convert_multiple
  File "formats/tiddlywiki.py", line 234, in convert
  File "formats/tiddlywiki.py", line 206, in convert_tid
ValueError: not enough values to unpack (expected 2, got 1)
[PYI-847015:ERROR] Failed to execute script 'jimmy_cli' due to unhandled exception!

```

**Comment by marph91** [comment]
Ah, that shouldn't happen, but it seems like some notes have a slightly different format. I made the parsing more robust. It should cover this error.

Here is the new release: https://github.com/marph91/jimmy/releases/tag/v0.0.38

**Comment by marph91** [comment]
Hi @gerroon, sorry for pinging. Is this issue still relevant or does the latest release work for you?

**Comment by gerroon** [comment]
Thanks, it worked much better after the fix.
