### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect, importing from any nsx file (Synology Note Station)

### ISSUE THREAD

**Issue by arthytrip** [marph91/jimmy#9]
**Describe the bug**
Unable to import to Joplin from any nsx file (Synology Note Station).
No matter if the nsx file is composed by one, few or many Synology notebooks; the error is always the same.

**OS**
Windows 11

**To Reproduce**
This is the command and the results on a simple, one notebook file

```
>jimmy-cli-windows.exe 20240730_192835_4731_test.nsx --format synology_note_station
[07/30/24 19:32:55] INFO     Importing notes from "20240730_192835_4731_test.nsx"
                    INFO     Start parsing
[07/30/24 19:33:05] INFO     Finished parsing: 2 notebooks, 23 notes, 13 resources
                    INFO     Start import to Joplin
Traceback (most recent call last):
  File "jimmy_cli.py", line 71, in <module>
  File "jimmy_cli.py", line 67, in main
  File "jimmy.py", line 111, in jimmy
  File "common.py", line 68, in create_progress_bars
  File "enlighten\manager.py", line 55, in get_manager
  File "enlighten\_manager.py", line 69, in __init__
  File "enlighten\_basemanager.py", line 74, in __init__
  File "blessed\terminal.py", line 167, in __init__
  File "jinxed\win32.py", line 331, in get_term
  File "jinxed\win32.py", line 181, in set_console_mode
  File "jinxed\win32.py", line 86, in _check_bool
OSError: [WinError 87] The parameter is incorrect.
[19200] Failed to execute script 'jimmy_cli' due to unhandled exception!
```

**Comment by marph91** [comment]
> No matter if the nsx file is composed by one, few or many Synology notebooks; the error is always the same.

This sounds like a general issue (with the progress bar implementation). Could you share which shell you are using? I couldn't reproduce with cmd, git bash and powershell.

**Comment by arthytrip** [comment]
> This sounds like a general issue (with the progress bar implementation). Could you share which shell you are using? I couldn't reproduce with cmd, git bash and powershell.

Hello, I'm using CMD in both administration and not administration mode. 
Tomorrow i could try with PowerShell.

**Comment by avylove** [comment]
Was the Windows version incorrectly reported above? It has Windows 10 there.

**Comment by arthytrip** [comment]
> Was the Windows version incorrectly reported above? It has Windows 10 there.

I apologize, W11 is the right version.
I corrected the first post.

**Comment by avylove** [comment]
Do you have python installed? If you do, could you run a few things in Python? If not, it's ok.

If you can, you'll need to install the jinxed package using pip.
Then either as a script or individual statements.

```
import sys
import msvcrt
from jinxed import win32

fd = sys.__stdout__.fileno()
print(fd)

filehandle = msvcrt.get_osfhandle(fd)
print(filehandle)

mode = win32.get_console_mode(filehandle)
print(mode)
print(mode & win32.ENABLE_VIRTUAL_TERMINAL_PROCESSING)

win32.set_console_mode(filehandle, mode | win32.ENABLE_VIRTUAL_TERMINAL_PROCESSING)
```

**Comment by marph91** [comment]
If you have the time, you can try the [latest jimmy release](https://github.com/marph91/jimmy/releases/tag/v0.0.10) with cmd. It contains a fix by @avylove.

**Comment by marph91** [comment]
Closed due to lack of feedback. Feel free to reopen if the issue persists.
